package com.sparg.java.dm.entity;

import java.lang.reflect.Field;
import java.lang.reflect.InvocationTargetException;
import java.sql.ResultSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * @author: vimal.sengoden
 * Date: 11/21/2014
 * Time: 3:14 PM
 */
public interface EntityManager<T> {
    public T getNewEntityInstance() throws InvocationTargetException, NoSuchMethodException, InstantiationException, IllegalAccessException;

    public String getTableName();

    public String getSourceQuery();

    public Field getPrimaryKey();

    boolean isPkAutoGenerated();

    public List<? extends Field> getBkFields();

    public List<? extends Field> getFkFields();

    public Map<Field, String> getFkFieldsWithTargetQuery();

    public List<? extends Field> getSourceFields();

    public List<? extends Field> getTargetFields();

    public List<? extends Field> getUpdateTargetFields();

    String createInsertQuery();

    String createUpdateQuery();

    String createDeleteQuery();

    Set<T> resultSetToSource(ResultSet rs) throws Exception;

    Set<T> resultSetToSource(ResultSet rs, Filter filter) throws Exception;

    Set<T> resultSetToSource(ResultSet rs, DuplicateHandler duplicateHandler) throws Exception;

    Set<T> resultSetToSource(ResultSet rs, Filter filter, DuplicateHandler duplicateHandler) throws Exception;
}
